---
ID: "c02609d4-87de-422c-86ab-89e0fac9a85d"
Parent: "9c275cb8-c46f-436e-8f27-102b3ae9d866"
Template: "2a3e91a0-7987-44b5-ab34-35c2d9de83b9"
Path: /sitecore/layout/Renderings/Stratum/Feature/PageContent/Products Listing
SharedFields:
- ID: "13f89250-ad6b-4548-882e-118a12c18094"
  Hint: Parameters Template
  Value: "{1E6AA4A5-6034-4949-B3D3-DC26F6054117}"
- ID: "1a7c85e5-dc0b-490d-9187-bb1dbcb4c72f"
  Hint: Datasource Template
  Value: 
- ID: "1c0af338-70a8-455f-8366-173135e03be6"
  Hint: Placeholder
  Value: main
- ID: "94069f66-609c-48b0-8281-521c30fb269d"
  Hint: Open Properties after Add
  Value: 1
- ID: "ded9e431-3604-4921-a4b3-a6ec7636a5b6"
  Hint: Controller Action
  Value: RenderProductsListing
- ID: "e64ad073-dfcc-4d20-8c0b-fe5aa6226cd7"
  Hint: Controller
  Value: Stratum.Feature.PageContent.Controllers.ProductsController,Stratum.Feature.PageContent
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230426T153245Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ce58912c-baec-4220-8da4-ccb925efa046"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230426T153951Z
