---
ID: "ee7ad6d7-6d84-4b18-ba2a-5a8eb59be16c"
Parent: "bea9d87a-2b58-4dc1-923f-fb5cf7869715"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Stratum/Foundation/Common/Base Email Template/Email Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230425T122806Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5901e38c-df14-49c4-b8ba-0dba62cfc58a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230426T151955Z
