---
ID: "d59f912e-e6c0-4561-b3cb-df3a2f2976b5"
Parent: "b0e484ce-a4da-4a68-b9d8-aaf6adc7ef9d"
Template: "b0e484ce-a4da-4a68-b9d8-aaf6adc7ef9d"
Path: /sitecore/templates/Stratum/Foundation/Common/Base Template/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230426T073422Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a6c33f1d-d5ae-4256-ac36-c69eb3c0c88f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230426T073422Z
