---
ID: "6370a31a-cf2f-4e8d-8c7a-00b567b8b3bb"
Parent: "3d6a3dd7-6b55-42b3-b4d9-f6a5742f1ef6"
Template: "3d6a3dd7-6b55-42b3-b4d9-f6a5742f1ef6"
Path: /sitecore/templates/Stratum/Foundation/Common/Pagination Settings/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "0a33fb6a-c9e7-4c81-a94f-db7975d30d42"
      Hint: Page Size
      Value: 5
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230425T121719Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "85068cef-4f82-4c1f-a884-434f742baa03"
      Hint: Show Pagination
      Value: 1
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3809703e-8a71-4b4d-81e7-30ed28a4c69b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230425T121914Z
