---
ID: "a470ebf6-3f8a-4d4e-bed4-cddaca99c7be"
Parent: "3eba1a1e-56a3-44a3-a7c0-e741fcfae8ce"
Template: "3eba1a1e-56a3-44a3-a7c0-e741fcfae8ce"
Path: /sitecore/templates/Stratum/Feature/PageContent/Teaser Tile/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230426T113027Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ce34bce7-8992-4d85-bdd6-3a19f1735e26"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230426T113027Z
