---
ID: "6b19370f-6741-4e3a-ac91-c0e2b387bd5f"
Parent: "bea9d87a-2b58-4dc1-923f-fb5cf7869715"
Template: "bea9d87a-2b58-4dc1-923f-fb5cf7869715"
Path: /sitecore/templates/Stratum/Foundation/Common/Base Email Template/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230425T122616Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9cf818eb-ec4a-42c8-8952-d239ffb26532"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230501T155019Z
